### ISSUE TITLE
lychee checks the content of the output Markdown format, and the content is output as a task list.

### ISSUE THREAD

**Issue by eryajf** [lycheeverse/lychee-action#153]
For example, outputting links as task lists will be very helpful for managers when they will deal with a large number of broken links.

<img width="753" alt="image" src="https://user-images.githubusercontent.com/33259379/183284467-88c6be7e-b69d-4b5d-8069-092e271940f8.png">

Just like the first one, but here I changed it manually.

**Comment by mre** [comment]
Hey that's a great idea!

**Comment by tooomm** [comment]
Do you want to change that for the action only? I assume for the created issues that can be helpful.
Keep in mind that the GitHub Summary is also based on the md output. But probably doesn't hurt to have check boxes there as well (they might not work in the workflow run overview though).

**Comment by mre** [comment]
Don't know. We could introduce another format (`--format github`), but on second thought I'm not sure if it's a good idea because the cli should be agnostic to how the output gets used. At the same time a todo list could be helpful in other situations as well, so maybe we could call it `--format todo`. Open for suggestions.

**Comment by mre** [comment]
I reflected on this as I went through the open issues and decided to not go forward with it for the time being. The reason is that I would like to keep the lychee CLI as simple as possible, and it should not know about to-do lists etc. If we want to add it to the lychee-action, we have to do a lot of output parsing etc.
The better way to do it would be to build a separate lychee-action, which uses the lychee-lib instead of the lychee-cli and presents the output in different ways. This would be a lot of work, though, because one would end up reimplementing the command line interface in the action. Not impossible, but quite a big task.

For these reasons, I decided to close the issue, but thanks for the discussion @tooomm.
